# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('facility', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('opening', models.IntegerField()),
                ('breaks', models.IntegerField()),
                ('sick', models.IntegerField()),
                ('closing', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
