# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('facility', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('opening', models.IntegerField()),
                ('breaks', models.IntegerField()),
                ('sick', models.IntegerField()),
                ('closing', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='breaks',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='closing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='opening',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sick',
        ),
    ]
