# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20170112_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='uid',
        ),
        migrations.AddField(
            model_name='response',
            name='rid',
            field=models.IntegerField(default=0),
        ),
    ]
