# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20170112_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='breaks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='closing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='opening',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='sick',
            field=models.IntegerField(default=0),
        ),
    ]
