# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20170112_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='response',
            name='rid',
        ),
        migrations.AddField(
            model_name='response',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='response',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
