# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_response_unique_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='clinic_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='response',
            name='mid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='response',
            name='facility',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
