# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_auto_20170124_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='zipcode',
            field=models.CharField(default='', max_length=5),
        ),
    ]
