# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20170124_2114'),
        ('form', '0009_auto_20170127_1529'),
    ]

    operations = [
    ]
